/**
* LAMP Platform
* The LAMP Platform API.
*
* The version of the OpenAPI document: 1.0.0
* Contact: team@digitalpsych.org
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package digital.lamp.lamp-core.models


import com.squareup.moshi.Json
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

import java.io.Serializable
/**
 * An event generated by a participant interacting with the LAMP app.
 * @param timestamp 
 * @param sensor The type of the sensor event.
 * @param data The item information recorded within the sensor event.
 */
@Parcelize

data class SensorEvent (
    @Json(name = "timestamp")
    var timestamp: java.sql.Timestamp? = null,
    /* The type of the sensor event. */
    @Json(name = "sensor")
    var sensor: kotlin.String? = null,
    /* The item information recorded within the sensor event. */
    @Json(name = "data")
    var data: kotlin.Any? = null
) : Serializable, Parcelable {
	companion object {
		private const val serialVersionUID: Long = 123
	}

}

